### ISSUE TITLE
Enable travis-ci

### ISSUE THREAD

**Issue by srghma** [purescript-codegen/purescript-ps-cst#1]
@paluh I have sent the request to allow me access to travis-ci for purescript-codegen organization

Could you approve please, tnx

**Comment by flip111** [comment]
I could probably do that too, but i don't know where i could see such a request ...

**Comment by paluh** [comment]
Oh sorry for delay. I'm not sure where to look for your request. I thought that we all have admin status, but I've found some additional switches in the org settings. Now I think we are all admins.
@srghma Could you please check if you are able to access travis-ci?

**Comment by srghma** [comment]
![2020-05-22-10:23:52-screenshot](https://user-images.githubusercontent.com/7573215/82642320-61aa8480-9c16-11ea-91b3-4707e66d418f.png)
![2020-05-22-10:23:57-screenshot](https://user-images.githubusercontent.com/7573215/82642325-62dbb180-9c16-11ea-9d65-045491ed1a9f.png)

no, I still dont have

no, I dont know where you could find it

**Comment by srghma** [comment]
@paluh hi, could you help me with permissions)

**Comment by flip111** [comment]
@srghma i approved your request, have fun.

**Comment by srghma** [comment]
@flip111 still cannot access

I see it enabled for me, but not in the list of repos in the travis site, wrote to support

but maybe there is a page like this in org settings page (I have no access)

https://cloud.githubusercontent.com/assets/10120600/10861162/6e5b607a-7f45-11e5-9614-999538d445cf.png

**Comment by srghma** [comment]
I signed out and in, and now I see
